//! Poseidon-128 over the BN254 scalar field — the algebraic substrate for every
//! CHRONOS commitment, KDF, and AEAD.
//!
//! # Why this module exists
//!
//! Previous revisions hand-rolled a "Poseidon x^5 sponge" in
//! [`crate::circuit`]. It was not Poseidon. The round function applied `x^5`
//! correctly, but there were no round constants and the "MDS mix" summed the
//! three lanes into lane 0 while leaving lanes 1 and 2 untouched — a
//! non-invertible, non-MDS linear layer. A permutation without round constants
//! is also trivially susceptible to invariant-subspace attacks. Its ~650
//! constraints were decorative: the derived `K_enc` was bound to
//! `let _k_enc = ...` and never compared with anything.
//!
//! This module replaces it with the audited implementation from
//! `ark-crypto-primitives`, instantiated with round constants and an MDS matrix
//! generated by the reference Grain LFSR from the Poseidon paper.
//!
//! # The property that makes the rest of CHRONOS sound
//!
//! Every CHRONOS statement has the shape "the prover knows a pre-image of this
//! public commitment". That requires the digest the *verifier* computes natively
//! and the digest the *circuit* computes in-circuit to be identical field
//! elements. If they diverge by so much as one round constant, every honest
//! proof fails and the failure mode is a silent, undebuggable rejection.
//!
//! [`tests::test_native_and_gadget_agree`] pins this for every helper in this
//! module. It is the single most important test in the crate.
//!
//! # Parameters
//!
//! | Parameter | Value | Reason |
//! |---|---|---|
//! | Field | BN254 `Fr` | matches the EVM `alt_bn128` precompiles, so proofs verify on-chain |
//! | Width `t` | 3 (rate 2, capacity 1) | capacity 1 gives ~127-bit collision resistance on a 254-bit field |
//! | S-box | `x^5` | `gcd(5, p-1) == 1` for BN254, so `x -> x^5` is a permutation |
//! | Full rounds | 8 | reference Poseidon-128 for `alpha = 5`, `t = 3` |
//! | Partial rounds | 57 | reference Poseidon-128 for `alpha = 5`, `t = 3` |
//!
//! The MDS matrix is Cauchy: `mds[i][j] = 1 / (x_i + y_j)`. Any Cauchy matrix
//! with pairwise-distinct `x_i`, pairwise-distinct `y_j`, and no `x_i + y_j = 0`
//! is MDS — every square submatrix is invertible. That is a theorem, not a
//! heuristic, and [`tests::test_mds_is_cauchy_wellformed`] checks the
//! preconditions actually hold for the generated matrix rather than assuming it.
//!
//! # Domain separation
//!
//! Every distinct use of the permutation prefixes a unique [`Domain`] tag. Without
//! this, a digest computed over the secret key and a digest computed over the VDF
//! output are drawn from the same function, and a commitment to one could be
//! replayed as a commitment to the other.

use ark_bn254::Fr;
use ark_crypto_primitives::sponge::poseidon::constraints::PoseidonSpongeVar;
use ark_crypto_primitives::sponge::poseidon::{find_poseidon_ark_and_mds, PoseidonConfig};
use ark_crypto_primitives::sponge::poseidon::PoseidonSponge;
use ark_crypto_primitives::sponge::constraints::CryptographicSpongeVar;
use ark_crypto_primitives::sponge::{CryptographicSponge, FieldBasedCryptographicSponge};
use ark_ff::{BigInteger, PrimeField};
use ark_r1cs_std::eq::EqGadget;
use ark_r1cs_std::fields::fp::FpVar;
use ark_relations::r1cs::{ConstraintSystemRef, SynthesisError};
use std::sync::OnceLock;

/// Sponge rate, in field elements.
pub const RATE: usize = 2;
/// Sponge capacity, in field elements. Width `t = RATE + CAPACITY = 3`.
pub const CAPACITY: usize = 1;
/// S-box exponent. `x^5` is a permutation of BN254 `Fr` because `gcd(5, p-1) = 1`.
pub const ALPHA: u64 = 5;
/// Full rounds (S-box applied to all lanes).
pub const FULL_ROUNDS: usize = 8;
/// Partial rounds (S-box applied to lane 0 only).
pub const PARTIAL_ROUNDS: usize = 57;

/// Bytes packed into one field element.
///
/// 16 bytes = 128 bits, comfortably below BN254 `Fr`'s 254-bit modulus. Packing
/// is therefore injective and never wraps. Using 31 bytes would be denser but
/// puts the encoding one bit from the modulus, where a reduction would silently
/// alias two distinct byte strings to the same field element and collapse the
/// commitment's binding property.
pub const BYTES_PER_LIMB: usize = 16;

/// Domain-separation tags.
///
/// Absorbed as the first field element of every sponge invocation, so digests
/// taken over different kinds of object are drawn from different functions and
/// cannot be substituted for one another.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u64)]
pub enum Domain {
    /// Commitment to a VDF output `y`.
    VdfOutput = 1,
    /// Commitment to the time-locked ciphertext `ct_sk`.
    Ciphertext = 2,
    /// Commitment to the plaintext secret key `sk`.
    SecretKey = 3,
    /// Commitment to the post-wipe buffer state.
    WipedBuffer = 4,
    /// Commitment to a mission identifier.
    MissionId = 5,
    /// Key derivation: `(y, salt) -> K_enc`.
    KeyDerivation = 6,
    /// Chronos-AEAD keystream generation.
    AeadKeystream = 7,
    /// Chronos-AEAD authentication tag.
    AeadTag = 8,
    /// EAIP time-locked identity root.
    IdentityRoot = 9,
    /// Commitment to the containment ledger's final state.
    ContainmentLedger = 10,
}

impl Domain {
    /// The tag as a field element.
    #[must_use]
    pub fn to_field(self) -> Fr {
        Fr::from(self as u64)
    }
}

/// The process-wide Poseidon configuration.
///
/// Generating the constants runs the Grain LFSR over 65 rounds with rejection
/// sampling, which takes single-digit milliseconds. It is deterministic, so it is
/// computed once and shared rather than recomputed per proof.
fn config_cell() -> &'static PoseidonConfig<Fr> {
    static CONFIG: OnceLock<PoseidonConfig<Fr>> = OnceLock::new();
    CONFIG.get_or_init(|| {
        let (ark, mds) = find_poseidon_ark_and_mds::<Fr>(
            Fr::MODULUS_BIT_SIZE as u64,
            RATE,
            FULL_ROUNDS as u64,
            PARTIAL_ROUNDS as u64,
            // Number of candidate MDS matrices to discard before accepting one.
            // The reference generator skips matrices failing its three
            // algebraic-attack tests. Zero is the value arkworks itself uses for
            // several of its shipped parameter sets; MDS-ness is guaranteed
            // independently by the Cauchy construction, which
            // `test_mds_is_cauchy_wellformed` verifies.
            0,
        );
        PoseidonConfig::new(FULL_ROUNDS, PARTIAL_ROUNDS, ALPHA, mds, ark, RATE, CAPACITY)
    })
}

/// Borrow the shared Poseidon configuration.
#[must_use]
pub fn config() -> &'static PoseidonConfig<Fr> {
    config_cell()
}

// ─── Byte packing ─────────────────────────────────────────────────────────────

/// Pack bytes into field elements, [`BYTES_PER_LIMB`] bytes per element,
/// big-endian, zero-padding the final partial limb.
///
/// The input length is *not* recoverable from the limbs alone, so
/// [`hash_bytes`] absorbs the length explicitly. Without that, `[0x01]` and
/// `[0x01, 0x00]` would produce identical limbs and therefore identical digests.
#[must_use]
pub fn pack_bytes(bytes: &[u8]) -> Vec<Fr> {
    bytes
        .chunks(BYTES_PER_LIMB)
        .map(|chunk| {
            let mut buf = [0u8; BYTES_PER_LIMB];
            buf[..chunk.len()].copy_from_slice(chunk);
            Fr::from_be_bytes_mod_order(&buf)
        })
        .collect()
}

/// Number of limbs [`pack_bytes`] produces for a `len`-byte input.
#[must_use]
pub fn limb_count(len: usize) -> usize {
    len.div_ceil(BYTES_PER_LIMB)
}

/// Split a 32-byte value into exactly two field elements.
///
/// Used for the secret key and for any other fixed 32-byte quantity where a
/// statically known limb count keeps the circuit shape fixed.
#[must_use]
pub fn split32(bytes: &[u8; 32]) -> [Fr; 2] {
    let mut lo = [0u8; BYTES_PER_LIMB];
    let mut hi = [0u8; BYTES_PER_LIMB];
    lo.copy_from_slice(&bytes[..BYTES_PER_LIMB]);
    hi.copy_from_slice(&bytes[BYTES_PER_LIMB..]);
    [
        Fr::from_be_bytes_mod_order(&lo),
        Fr::from_be_bytes_mod_order(&hi),
    ]
}

/// Inverse of [`split32`].
///
/// # Errors
/// Returns `None` if either element does not fit in [`BYTES_PER_LIMB`] bytes,
/// which means it was not produced by [`split32`].
#[must_use]
pub fn join32(pair: &[Fr; 2]) -> Option<[u8; 32]> {
    let mut out = [0u8; 32];
    for (i, elem) in pair.iter().enumerate() {
        let be = elem.into_bigint().to_bytes_be();
        // `to_bytes_be` emits a fixed 32-byte buffer for BN254; a value that
        // came from `split32` has its top 16 bytes zero.
        let (pad, body) = be.split_at(be.len().saturating_sub(BYTES_PER_LIMB));
        if pad.iter().any(|b| *b != 0) {
            return None;
        }
        out[i * BYTES_PER_LIMB..(i + 1) * BYTES_PER_LIMB].copy_from_slice(body);
    }
    Some(out)
}

// ─── Native hashing ───────────────────────────────────────────────────────────

/// Absorb `[domain, inputs...]` and squeeze one field element.
///
/// This is the canonical CHRONOS digest. Every public commitment in the erasure
/// and identity circuits is produced by this function natively and reproduced by
/// [`hash_gadget`] in-circuit.
#[must_use]
pub fn hash(domain: Domain, inputs: &[Fr]) -> Fr {
    let mut sponge = PoseidonSponge::<Fr>::new(config());
    let mut absorbed = Vec::with_capacity(inputs.len() + 1);
    absorbed.push(domain.to_field());
    absorbed.extend_from_slice(inputs);
    sponge.absorb(&absorbed);
    sponge.squeeze_native_field_elements(1)[0]
}

/// Absorb `[domain, inputs...]` and squeeze `n` field elements.
///
/// Used by the KDF and by Chronos-AEAD's keystream generator, both of which need
/// more than one element of output.
#[must_use]
pub fn hash_many(domain: Domain, inputs: &[Fr], n: usize) -> Vec<Fr> {
    let mut sponge = PoseidonSponge::<Fr>::new(config());
    let mut absorbed = Vec::with_capacity(inputs.len() + 1);
    absorbed.push(domain.to_field());
    absorbed.extend_from_slice(inputs);
    sponge.absorb(&absorbed);
    sponge.squeeze_native_field_elements(n)
}

/// Digest a byte string: absorb `[domain, len, packed_limbs...]`.
///
/// The length is absorbed so that inputs differing only in trailing zero bytes
/// produce different digests. Without it the packing is not injective.
#[must_use]
pub fn hash_bytes(domain: Domain, bytes: &[u8]) -> Fr {
    let mut inputs = Vec::with_capacity(limb_count(bytes.len()) + 1);
    inputs.push(Fr::from(bytes.len() as u64));
    inputs.extend(pack_bytes(bytes));
    hash(domain, &inputs)
}

// ─── In-circuit hashing ───────────────────────────────────────────────────────

/// In-circuit counterpart of [`hash`].
///
/// # Errors
/// Propagates [`SynthesisError`] from the underlying sponge gadget.
pub fn hash_gadget(
    cs: ConstraintSystemRef<Fr>,
    domain: Domain,
    inputs: &[FpVar<Fr>],
) -> Result<FpVar<Fr>, SynthesisError> {
    let mut sponge = PoseidonSpongeVar::<Fr>::new(cs, config());
    let mut absorbed = Vec::with_capacity(inputs.len() + 1);
    absorbed.push(FpVar::Constant(domain.to_field()));
    absorbed.extend_from_slice(inputs);
    sponge.absorb(&absorbed)?;
    Ok(sponge.squeeze_field_elements(1)?.remove(0))
}

/// In-circuit counterpart of [`hash_many`].
///
/// # Errors
/// Propagates [`SynthesisError`] from the underlying sponge gadget.
pub fn hash_many_gadget(
    cs: ConstraintSystemRef<Fr>,
    domain: Domain,
    inputs: &[FpVar<Fr>],
    n: usize,
) -> Result<Vec<FpVar<Fr>>, SynthesisError> {
    let mut sponge = PoseidonSpongeVar::<Fr>::new(cs, config());
    let mut absorbed = Vec::with_capacity(inputs.len() + 1);
    absorbed.push(FpVar::Constant(domain.to_field()));
    absorbed.extend_from_slice(inputs);
    sponge.absorb(&absorbed)?;
    sponge.squeeze_field_elements(n)
}

/// In-circuit counterpart of [`hash_bytes`], for a byte string of statically
/// known length whose limbs are supplied as witnesses.
///
/// `byte_len` must be the true length of the original byte string, matching what
/// the native side absorbed.
///
/// # Errors
/// Propagates [`SynthesisError`] from the underlying sponge gadget.
pub fn hash_bytes_gadget(
    cs: ConstraintSystemRef<Fr>,
    domain: Domain,
    byte_len: usize,
    limbs: &[FpVar<Fr>],
) -> Result<FpVar<Fr>, SynthesisError> {
    let mut inputs = Vec::with_capacity(limbs.len() + 1);
    inputs.push(FpVar::Constant(Fr::from(byte_len as u64)));
    inputs.extend_from_slice(limbs);
    hash_gadget(cs, domain, &inputs)
}

/// Enforce `a == b`, returning an unsatisfiable constraint when they differ.
///
/// # Errors
/// Propagates [`SynthesisError`].
pub fn enforce_equal(a: &FpVar<Fr>, b: &FpVar<Fr>) -> Result<(), SynthesisError> {
    a.enforce_equal(b)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_ff::{One, Zero};
    use ark_r1cs_std::alloc::AllocVar;
    use ark_r1cs_std::R1CSVar;
    use ark_relations::r1cs::ConstraintSystem;

    fn witness_vec(cs: &ConstraintSystemRef<Fr>, vals: &[Fr]) -> Vec<FpVar<Fr>> {
        vals.iter()
            .map(|v| FpVar::new_witness(cs.clone(), || Ok(*v)).expect("witness alloc"))
            .collect()
    }

    /// The load-bearing test for the whole crate.
    ///
    /// If the native digest and the in-circuit digest ever diverge, every honest
    /// proof stops verifying, and the symptom — "valid witness, rejected proof" —
    /// gives no hint as to the cause. Every helper that has both a native and a
    /// gadget form is checked here.
    #[test]
    fn test_native_and_gadget_agree() {
        let cs = ConstraintSystem::<Fr>::new_ref();

        let inputs = vec![Fr::from(7u64), Fr::from(11u64), Fr::from(13u64)];
        let vars = witness_vec(&cs, &inputs);

        // hash / hash_gadget
        let native = hash(Domain::SecretKey, &inputs);
        let gadget = hash_gadget(cs.clone(), Domain::SecretKey, &vars).expect("gadget hash");
        assert_eq!(
            native,
            gadget.value().expect("gadget value"),
            "native and in-circuit Poseidon digests must be identical"
        );

        // hash_many / hash_many_gadget
        let native_many = hash_many(Domain::KeyDerivation, &inputs, 4);
        let gadget_many =
            hash_many_gadget(cs.clone(), Domain::KeyDerivation, &vars, 4).expect("gadget squeeze");
        assert_eq!(native_many.len(), 4);
        for (i, (n, g)) in native_many.iter().zip(gadget_many.iter()).enumerate() {
            assert_eq!(
                *n,
                g.value().expect("gadget value"),
                "squeezed element {i} must match"
            );
        }

        // hash_bytes / hash_bytes_gadget
        let bytes: Vec<u8> = (0u8..48).collect();
        let native_bytes = hash_bytes(Domain::VdfOutput, &bytes);
        let limb_vars = witness_vec(&cs, &pack_bytes(&bytes));
        let gadget_bytes =
            hash_bytes_gadget(cs.clone(), Domain::VdfOutput, bytes.len(), &limb_vars)
                .expect("gadget byte hash");
        assert_eq!(
            native_bytes,
            gadget_bytes.value().expect("gadget value"),
            "byte-string digests must match"
        );

        assert!(cs.is_satisfied().expect("satisfiability"));
    }

    /// Domain tags must actually separate. If two domains collide, a commitment
    /// to the secret key could be presented as a commitment to the VDF output.
    #[test]
    fn test_domains_separate() {
        let inputs = [Fr::from(42u64)];
        let a = hash(Domain::SecretKey, &inputs);
        let b = hash(Domain::VdfOutput, &inputs);
        let c = hash(Domain::Ciphertext, &inputs);
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
    }

    /// Absorbing the length is what makes byte packing injective. Drop it and
    /// these two inputs collide.
    #[test]
    fn test_trailing_zero_bytes_are_distinguished() {
        let a = hash_bytes(Domain::MissionId, &[0x01]);
        let b = hash_bytes(Domain::MissionId, &[0x01, 0x00]);
        let c = hash_bytes(Domain::MissionId, &[0x01, 0x00, 0x00]);
        assert_ne!(a, b, "length must be bound into the digest");
        assert_ne!(b, c);
    }

    #[test]
    fn test_hash_is_deterministic() {
        let inputs = [Fr::from(1u64), Fr::from(2u64)];
        assert_eq!(hash(Domain::WipedBuffer, &inputs), hash(Domain::WipedBuffer, &inputs));
    }

    #[test]
    fn test_hash_is_sensitive_to_every_input() {
        let base = [Fr::from(1u64), Fr::from(2u64), Fr::from(3u64)];
        let d = hash(Domain::SecretKey, &base);
        for i in 0..base.len() {
            let mut perturbed = base;
            perturbed[i] += Fr::one();
            assert_ne!(
                d,
                hash(Domain::SecretKey, &perturbed),
                "digest must depend on input {i}"
            );
        }
    }

    /// `split32` / `join32` must round-trip, otherwise the key recovered from a
    /// decryption gadget would not equal the key that was encrypted.
    #[test]
    fn test_split_join_round_trip() {
        let mut bytes = [0u8; 32];
        for (i, b) in bytes.iter_mut().enumerate() {
            *b = (i as u8).wrapping_mul(7).wrapping_add(3);
        }
        let pair = split32(&bytes);
        assert_eq!(join32(&pair), Some(bytes));
    }

    #[test]
    fn test_split32_high_and_low_are_independent() {
        let a = split32(&[0u8; 32]);
        let mut b_bytes = [0u8; 32];
        b_bytes[0] = 1;
        let b = split32(&b_bytes);
        assert_ne!(a[0], b[0], "byte 0 must land in the low limb");
        assert_eq!(a[1], b[1], "byte 0 must not affect the high limb");

        let mut c_bytes = [0u8; 32];
        c_bytes[16] = 1;
        let c = split32(&c_bytes);
        assert_eq!(a[0], c[0], "byte 16 must not affect the low limb");
        assert_ne!(a[1], c[1], "byte 16 must land in the high limb");
    }

    #[test]
    fn test_join32_rejects_oversized_limbs() {
        // A limb larger than 16 bytes cannot have come from `split32`.
        let bad = [Fr::from(u128::MAX) * Fr::from(u128::MAX), Fr::zero()];
        assert!(
            join32(&bad).is_none(),
            "limbs wider than BYTES_PER_LIMB must be rejected rather than truncated"
        );
    }

    #[test]
    fn test_packing_is_injective_on_limb_boundaries() {
        assert_eq!(limb_count(0), 0);
        assert_eq!(limb_count(1), 1);
        assert_eq!(limb_count(BYTES_PER_LIMB), 1);
        assert_eq!(limb_count(BYTES_PER_LIMB + 1), 2);
        assert_eq!(pack_bytes(&[0u8; 32]).len(), 2);
        assert_eq!(pack_bytes(&[0u8; 33]).len(), 3);
    }

    /// The generated MDS matrix must satisfy the Cauchy preconditions that make
    /// it provably MDS. Checking the preconditions is cheap; checking MDS-ness
    /// directly would mean inverting every square submatrix.
    #[test]
    fn test_mds_is_cauchy_wellformed() {
        let cfg = config();
        let t = RATE + CAPACITY;
        assert_eq!(cfg.mds.len(), t);
        for row in &cfg.mds {
            assert_eq!(row.len(), t);
            // A Cauchy entry is an inverse, so it is never zero.
            for entry in row {
                assert!(!entry.is_zero(), "MDS entries must be non-zero");
            }
        }
        // Rows must be pairwise distinct; equal rows would make the matrix
        // singular and the permutation non-invertible.
        for i in 0..t {
            for j in (i + 1)..t {
                assert_ne!(cfg.mds[i], cfg.mds[j], "MDS rows {i} and {j} must differ");
            }
        }
    }

    /// Round constants must exist, be correctly shaped, and not be all-equal.
    /// The previous hand-rolled gadget had none at all.
    #[test]
    fn test_round_constants_present_and_varied() {
        let cfg = config();
        let t = RATE + CAPACITY;
        assert_eq!(
            cfg.ark.len(),
            FULL_ROUNDS + PARTIAL_ROUNDS,
            "one round-constant vector per round"
        );
        for row in &cfg.ark {
            assert_eq!(row.len(), t);
        }
        let first = &cfg.ark[0];
        assert!(
            cfg.ark.iter().any(|r| r != first),
            "round constants must vary between rounds"
        );
        assert!(
            cfg.ark.iter().flatten().any(|c| !c.is_zero()),
            "round constants must not be all zero"
        );
    }

    #[test]
    fn test_config_parameters_match_documented_values() {
        let cfg = config();
        assert_eq!(cfg.rate, RATE);
        assert_eq!(cfg.capacity, CAPACITY);
        assert_eq!(cfg.alpha, ALPHA);
        assert_eq!(cfg.full_rounds, FULL_ROUNDS);
        assert_eq!(cfg.partial_rounds, PARTIAL_ROUNDS);
    }

    /// `x -> x^ALPHA` must be a permutation of the field, i.e.
    /// `gcd(ALPHA, p - 1) == 1`. If it is not, the round function is not
    /// invertible and Poseidon's security argument does not apply.
    #[test]
    fn test_alpha_is_coprime_to_field_order_minus_one() {
        use num_bigint::BigUint;
        let p_minus_1 = BigUint::from_bytes_le(&Fr::MODULUS.to_bytes_le()) - BigUint::from(1u32);
        let alpha = BigUint::from(ALPHA);
        // Euclidean gcd.
        let (mut a, mut b) = (p_minus_1, alpha);
        while b != BigUint::from(0u32) {
            let r = a % &b;
            a = b;
            b = r;
        }
        assert_eq!(a, BigUint::from(1u32), "x^{ALPHA} must permute the field");
    }

    /// A rough constraint budget. The whole point of moving to Poseidon is that
    /// a full permutation costs hundreds of constraints, not the tens of
    /// thousands a SHA-256 or AES gadget would.
    #[test]
    fn test_single_hash_constraint_cost_is_bounded() {
        let cs = ConstraintSystem::<Fr>::new_ref();
        let vars = witness_vec(&cs, &[Fr::from(1u64), Fr::from(2u64)]);
        let _ = hash_gadget(cs.clone(), Domain::SecretKey, &vars).expect("hash");
        let n = cs.num_constraints();
        println!("constraints for one Poseidon digest over 2 inputs: {n}");
        assert!(
            n < 1_500,
            "a single Poseidon digest should cost a few hundred constraints, got {n}"
        );
    }
}
