//! The VDF group modulus.
//!
//! # The bug this file used to contain
//!
//! The fallback constant was documented as "RSA-2048 from the RSA Factoring
//! Challenge (unfactored as of 2024)". It was not that number. It had **618**
//! decimal digits where RSA-2048 has 617, and ended `...207203575` where the
//! genuine value ends `...20720357` — a spurious trailing `5`.
//!
//! Three consequences, in increasing order of severity:
//!
//! 1. The citation was false. The value was `RSA-2048 * 10 + 5`, a 2052-bit
//!    integer with no published hardness analysis, so nothing was known about its
//!    factorization.
//! 2. Ending in `5`, it was divisible by 5. A modulus for a group of unknown order
//!    should be a product of two large primes; this one had a factor anybody can
//!    find by inspection. The remaining cofactor is a random 2049-bit integer,
//!    which has small prime factors with high probability. If enough of them are
//!    findable, `φ(N)` becomes computable and **the VDF's sequentiality guarantee
//!    disappears entirely** — the agent could unseal its key immediately instead
//!    of after `T` squarings, which is the single property CHRONOS exists to
//!    provide.
//! 3. At 2052 bits it serialised to 257 bytes, one byte over the 256-byte width
//!    the erasure circuit fixes for the VDF output. That is how it was caught: a
//!    length assertion in the lifecycle test, not a cryptographic review.
//!
//! The value is corrected below and [`tests`] now pins the digit count, the exact
//! bit length, and the absence of small factors, so a transcription error cannot
//! recur silently.
//!
//! # Why a hardcoded modulus is acceptable here at all
//!
//! For a VDF, `N` need not be secret — only its factorization. RSA-2048 is
//! published, was generated by RSA Security in 1991 with its factors destroyed,
//! and remains unfactored, so it is a legitimate nothing-up-my-sleeve choice for a
//! group of unknown order. It is standard practice in VDF deployments.
//!
//! The genuine limitation is different and is not fixed by any ceremony: a single
//! fixed modulus is shared by every CHRONOS deployment, so all deployments live in
//! the same group. See `chronos-provision` for the per-mission alternative and for
//! why the paper's claim that MPC generation is *mandatory* is too strong.

use crate::error::{ChronosError, ChronosResult};
use num_bigint::BigUint;
use num_traits::Zero;
use std::path::Path;

/// RSA-2048, from the RSA Factoring Challenge. 617 decimal digits, 2048 bits.
///
/// Published by RSA Security in 1991; the factors were destroyed and it has never
/// been factored. Cross-checkable against
/// <https://en.wikipedia.org/wiki/RSA_numbers#RSA-2048>.
///
/// Do not edit this without re-running [`tests::test_prototype_modulus_is_exactly_rsa_2048`],
/// which pins the digit count, bit length, byte width and last digits. A one-digit
/// transcription error here silently removes the VDF's security.
const RSA_2048: &str = "25195908475657893494027183240048398571429282126204032027777137836043662020707595556264018525880784406918290641249515082189298559149176184502808489120072844992687392807287776735971418347270261896375014971824691165077613379859095700097330459748808428401797429100642458691817195118746121515172654632282216869987549182422433637259085141865462043576798423387184774447920739934236584823824281198163815010674810451660377306056201619676256133844143603833904414952634432190114657544454178424020924616515723350778707749817125772467962926386356373289912154831438167899885040445364023527381951378636564391212010397122822120720357";

/// Required modulus width in bits.
///
/// Exact rather than a minimum, because the erasure circuit fixes the VDF output
/// at [`MODULUS_BYTES`] bytes. A wider modulus produces outputs the circuit cannot
/// represent — which is precisely the failure the old 2052-bit constant caused.
pub const MODULUS_BITS: u64 = 2048;

/// Required modulus width in bytes. Must equal `chronos_snark::circuit::Y_BYTES`.
pub const MODULUS_BYTES: usize = (MODULUS_BITS / 8) as usize;

/// Small primes rejected as factors of a candidate modulus.
///
/// A modulus for a group of unknown order must not have factors anybody can find
/// by trial division. This does not prove the modulus is hard — that is not
/// decidable here — but it catches the class of error that produced the 618-digit
/// constant, where the value was divisible by 5.
const SMALL_PRIME_SIEVE: [u32; 25] = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
];

/// The RSA modulus used as the VDF group order.
#[derive(Debug, Clone)]
pub struct MpcCertificate {
    /// The modulus `N`. Public; only its factorization must be unknown.
    pub n: BigUint,
}

impl MpcCertificate {
    /// Load `N` from `path`, falling back to [`RSA_2048`] when absent.
    ///
    /// # Validation
    ///
    /// Whichever source is used, `N` must be exactly [`MODULUS_BITS`] bits and
    /// free of small factors. The previous implementation accepted anything at or
    /// above 512 bits, which is why a 2052-bit value with a factor of 5 passed
    /// unremarked.
    ///
    /// # Errors
    /// Returns [`ChronosError::MpcCert`] if the file exists but is unreadable or
    /// empty, or if the resulting modulus fails validation.
    pub fn load<P: AsRef<Path>>(path: P) -> ChronosResult<Self> {
        let path_ref = path.as_ref();

        let n = match std::fs::read(path_ref) {
            Ok(data) if !data.is_empty() => {
                let n = BigUint::from_bytes_be(&data);
                tracing::info!(
                    target: "chronos",
                    path = %path_ref.display(),
                    bits = n.bits(),
                    "modulus loaded from file"
                );
                n
            }
            Ok(_) => {
                return Err(ChronosError::MpcCert(format!(
                    "modulus file '{}' is empty — corrupt or wrong path",
                    path_ref.display()
                )));
            }
            Err(_) => {
                tracing::warn!(
                    target: "chronos",
                    path = %path_ref.display(),
                    "modulus file not found — falling back to the published RSA-2048 challenge \
                     modulus. Every deployment using this fallback shares one group; use \
                     chronos-provision to generate a per-mission modulus."
                );
                RSA_2048.parse::<BigUint>().map_err(|e| {
                    ChronosError::MpcCert(format!("built-in RSA-2048 constant failed to parse: {e}"))
                })?
            }
        };

        validate_modulus(&n)?;
        Ok(Self { n })
    }

    /// The published RSA-2048 modulus, validated.
    ///
    /// # Errors
    /// Returns [`ChronosError::MpcCert`] if the built-in constant fails validation,
    /// which would mean it has been edited incorrectly.
    pub fn rsa_2048() -> ChronosResult<Self> {
        let n = RSA_2048
            .parse::<BigUint>()
            .map_err(|e| ChronosError::MpcCert(format!("RSA-2048 constant failed to parse: {e}")))?;
        validate_modulus(&n)?;
        Ok(Self { n })
    }
}

/// Reject moduli that are the wrong width or have easily-found factors.
///
/// # Errors
/// Returns [`ChronosError::MpcCert`] describing the first problem found.
pub fn validate_modulus(n: &BigUint) -> ChronosResult<()> {
    if n.bits() != MODULUS_BITS {
        return Err(ChronosError::MpcCert(format!(
            "modulus must be exactly {MODULUS_BITS} bits, got {}. The erasure circuit fixes the \
             VDF output at {MODULUS_BYTES} bytes, so a different width cannot be represented.",
            n.bits()
        )));
    }
    if n.to_bytes_be().len() != MODULUS_BYTES {
        return Err(ChronosError::MpcCert(format!(
            "modulus must serialise to exactly {MODULUS_BYTES} bytes, got {}",
            n.to_bytes_be().len()
        )));
    }
    for p in SMALL_PRIME_SIEVE {
        if (n % BigUint::from(p)).is_zero() {
            return Err(ChronosError::MpcCert(format!(
                "modulus is divisible by {p} — a VDF group of unknown order must not have \
                 trivially discoverable factors, since knowing the factorisation yields phi(N) \
                 and removes the sequential-work guarantee entirely"
            )));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Pins every property of the constant that the old value got wrong.
    ///
    /// If this test fails, someone has edited [`RSA_2048`]. Do not "fix" the test —
    /// restore the constant.
    #[test]
    fn test_prototype_modulus_is_exactly_rsa_2048() {
        assert_eq!(
            RSA_2048.len(),
            617,
            "RSA-2048 has exactly 617 decimal digits; the previous constant had 618"
        );
        assert!(
            RSA_2048.ends_with("20720357"),
            "RSA-2048 ends in 20720357; the previous constant ended in 207203575"
        );
        assert!(
            !RSA_2048.ends_with('5'),
            "a modulus ending in 5 is divisible by 5 and unusable as a group of unknown order"
        );

        let n = RSA_2048.parse::<BigUint>().expect("must parse");
        assert_eq!(n.bits(), 2048, "must be exactly 2048 bits");
        assert_eq!(
            n.to_bytes_be().len(),
            256,
            "must serialise to 256 bytes so it fits the circuit's fixed y width"
        );
    }

    /// The specific defect: divisibility by 5.
    #[test]
    fn test_modulus_has_no_small_factors() {
        let n = RSA_2048.parse::<BigUint>().expect("must parse");
        for p in SMALL_PRIME_SIEVE {
            assert!(
                !(&n % BigUint::from(p)).is_zero(),
                "RSA-2048 must not be divisible by {p}"
            );
        }
    }

    #[test]
    fn test_rsa_2048_accessor_validates() {
        let cert = MpcCertificate::rsa_2048().expect("built-in modulus must validate");
        assert_eq!(cert.n.bits(), MODULUS_BITS);
    }

    #[test]
    fn test_load_missing_file_uses_validated_fallback() {
        let cert = MpcCertificate::load("/definitely/not/a/real/path/certN.bin")
            .expect("missing file must fall back");
        assert_eq!(cert.n.bits(), MODULUS_BITS);
        assert_eq!(cert.n.to_bytes_be().len(), MODULUS_BYTES);
    }

    /// The width check that would have caught the old constant.
    #[test]
    fn test_validate_rejects_wrong_width() {
        let too_small = BigUint::from(7u32);
        assert!(validate_modulus(&too_small).is_err());

        // Exactly one bit too wide — the 2052-bit failure mode, scaled down.
        let n = RSA_2048.parse::<BigUint>().expect("parse");
        let too_wide = &n << 1;
        let err = validate_modulus(&too_wide).expect_err("2049 bits must be rejected");
        assert!(
            format!("{err}").contains("exactly 2048 bits"),
            "error should name the width requirement, got: {err}"
        );
    }

    /// Reconstruct the exact old value and confirm it is now rejected.
    #[test]
    fn test_validate_rejects_the_previous_buggy_constant() {
        let buggy: BigUint = format!("{RSA_2048}5")
            .parse()
            .expect("the old constant was RSA-2048 with a trailing 5");

        assert_eq!(buggy.to_bytes_be().len(), 257, "the old value was 257 bytes");
        assert!(
            (&buggy % BigUint::from(5u32)).is_zero(),
            "the old value was divisible by 5"
        );

        let err = validate_modulus(&buggy)
            .expect_err("the previously shipped modulus must now be rejected");
        // Width is checked first, so that is the error surfaced.
        assert!(format!("{err}").contains("2048 bits"));
    }

    #[test]
    fn test_validate_rejects_small_factors_at_correct_width() {
        // A 2048-bit even number: right width, trivially factorable.
        let mut n = BigUint::from(1u32) << 2047;
        n += BigUint::from(2u32); // still 2048 bits, still even
        let err = validate_modulus(&n).expect_err("an even modulus must be rejected");
        assert!(
            format!("{err}").contains("divisible by 2"),
            "error should name the factor, got: {err}"
        );
    }

    #[test]
    fn test_load_rejects_empty_file() {
        let dir = std::env::temp_dir();
        let path = dir.join(format!("chronos-empty-cert-{}.bin", std::process::id()));
        std::fs::write(&path, b"").expect("write");
        assert!(MpcCertificate::load(&path).is_err());
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_load_accepts_valid_file() {
        let dir = std::env::temp_dir();
        let path = dir.join(format!("chronos-good-cert-{}.bin", std::process::id()));
        let n = RSA_2048.parse::<BigUint>().expect("parse");
        std::fs::write(&path, n.to_bytes_be()).expect("write");

        let cert = MpcCertificate::load(&path).expect("a valid modulus file must load");
        assert_eq!(cert.n, n);

        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn test_modulus_bytes_matches_bits() {
        assert_eq!(MODULUS_BYTES, 256);
        assert_eq!(MODULUS_BITS as usize, MODULUS_BYTES * 8);
    }
}
