[package]
name = "chronos-vdf"
version = "0.1.0"
edition = "2021"

[dependencies]
chronos-core = { path = "../chronos-core" }
tokio = { workspace = true }
sha2 = { workspace = true }
gmp-mpfr-sys = { workspace = true }
num-bigint = { workspace = true }
thiserror = { workspace = true }
libc = { workspace = true }
