#!/usr/bin/env bash
#
# CHRONOS end-to-end demonstration.
#
# Walks the full protocol across the provisioner/agent/verifier boundary and ends
# with a verifier accepting a 128-byte proof it can check without trusting the
# agent.
#
# Nothing here is staged. The VDF performs real sequential squarings, the key is
# genuinely sealed and genuinely opened, and the proof is generated by the agent
# and verified against commitments the agent did not choose.
#
# Authentication is disabled for this run. That is a legitimate configuration and
# not a shortcut: the agent permits it only when bound to loopback, and refuses to
# start otherwise. Every endpoint would normally also require an X-Chronos-Auth
# HMAC over method, path, nonce and body digest; reproducing that in a shell
# script would obscure the protocol this script exists to show.
#
# Usage:
#   ./scripts/demo.sh                 # default T = 2,000,000 (~8s of VDF work)
#   T=10000000 ./scripts/demo.sh      # longer lock
#   KEEP=1 ./scripts/demo.sh          # retain the working directory
#
# Requires: cargo, curl, python3 (for JSON extraction and hex conversion).

set -euo pipefail

T="${T:-2000000}"
PORT="${PORT:-8080}"
KEEP="${KEEP:-}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEMO_DIR="$REPO_ROOT/demo-run"
BASE="http://127.0.0.1:$PORT"

AGENT_PID=""
STEP=0

# ── Presentation helpers ─────────────────────────────────────────────────────
# The terminal output is the story, so the banners matter as much as the logic.

if [ -t 1 ]; then
  C_HEAD=$'\033[36m'; C_RULE=$'\033[36;2m'; C_STEP=$'\033[33m'
  C_DIM=$'\033[90m';  C_OK=$'\033[32m';    C_BAD=$'\033[31m'
  C_VAL=$'\033[97m';  C_OFF=$'\033[0m'
else
  C_HEAD=''; C_RULE=''; C_STEP=''; C_DIM=''; C_OK=''; C_BAD=''; C_VAL=''; C_OFF=''
fi

banner() { printf '\n%s%s%s\n  %s%s%s\n%s%s%s\n' \
            "$C_RULE" "$(printf '=%.0s' {1..74})" "$C_OFF" \
            "$C_HEAD" "$1" "$C_OFF" \
            "$C_RULE" "$(printf '=%.0s' {1..74})" "$C_OFF"; }
step()   { STEP=$((STEP + 1)); printf '\n%s[%d] %s%s\n' "$C_STEP" "$STEP" "$1" "$C_OFF"; }
detail() { printf '%s    %s%s\n' "$C_DIM" "$1" "$C_OFF"; }
good()   { printf '%s    OK  %s%s\n' "$C_OK" "$1" "$C_OFF"; }
bad()    { printf '%s    !!  %s%s\n' "$C_BAD" "$1" "$C_OFF"; }
val()    { printf '%s      %s%s\n' "$C_VAL" "$1" "$C_OFF"; }

cleanup() {
  local rc=$?
  if [ -n "$AGENT_PID" ] && kill -0 "$AGENT_PID" 2>/dev/null; then
    detail 'stopping agent'
    kill "$AGENT_PID" 2>/dev/null || true
    wait "$AGENT_PID" 2>/dev/null || true
  fi
  if [ $rc -ne 0 ] && [ -f "$DEMO_DIR/agent.stderr.log" ]; then
    printf '\n'; detail 'agent stderr (last 40 lines):'
    tail -n 40 "$DEMO_DIR/agent.stderr.log" | sed 's/^/      /'
  fi
  if [ -z "$KEEP" ] && [ -d "$DEMO_DIR" ]; then
    detail 'removing working directory (set KEEP=1 to retain it)'
    rm -rf "$DEMO_DIR"
  fi
  printf '\n'
  exit $rc
}
trap cleanup EXIT INT TERM

# A fresh 24-hex-character nonce is required even with authentication disabled:
# replay protection and authentication are independent controls, and only the
# latter is switched off here.
nonce() { head -c 12 /dev/urandom | od -An -tx1 | tr -d ' \n'; }

# Emits "<status> <body>" so callers can branch on the code.
req() {
  local method="$1" path="$2" body_file="${3:-}"
  local args=(-s -w '\n%{http_code}' -X "$method"
              -H "X-Chronos-Nonce: $(nonce)" --max-time 30)
  if [ -n "$body_file" ]; then
    args+=(-H 'Content-Type: application/octet-stream' --data-binary "@$body_file")
  fi
  local out; out="$(curl "${args[@]}" "$BASE$path" || true)"
  local code="${out##*$'\n'}" payload="${out%$'\n'*}"
  printf '%s\t%s' "$code" "$payload"
}

jget() { python3 -c 'import json,sys; print(json.load(sys.stdin).get(sys.argv[1], ""))' "$1"; }

banner 'CHRONOS - end-to-end demonstration'
detail "repository : $REPO_ROOT"
detail "T          : $T sequential squarings"
detail "API        : $BASE (loopback, authentication disabled)"

# ── 0. Build ─────────────────────────────────────────────────────────────────
step 'Building release binaries'
detail 'first run compiles the dependency tree; subsequent runs are fast'
cargo build --release -p chronos-provision -p chronos-agent >/dev/null 2>&1 \
  || { bad 'cargo build failed - run it directly to see the error'; exit 1; }
good 'chronos-provision and chronos-agent built'

# ── 1. Clean working directory ───────────────────────────────────────────────
step 'Preparing a clean working directory'
rm -rf "$DEMO_DIR"
mkdir -p "$DEMO_DIR/config"

# The agent loads config/default.toml relative to its working directory, and that
# source is required rather than optional, so it must exist here.
cat > "$DEMO_DIR/config/default.toml" <<EOF
# Generated by scripts/demo.sh - not for production use.
[paths]
mission_public = "mission_public.json"
ct_sk          = "ct_sk.bin"
salt           = "salt.bin"
cert_n         = "certN.bin"
proving_key    = "erasure_pk.bin"

[auth]
# Permitted only because api_addr below is loopback. The agent refuses to start
# with authentication disabled on any routable address.
enabled = false

[network]
drand_url          = "https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/public/latest"
drand_timeout_secs = 10
# The sealing key is derived from (y, salt), so the salt must be the one the
# provisioner sealed under. A live beacon would be a different value.
fetch_live_beacon  = false

[server]
api_addr     = "127.0.0.1:$PORT"
metrics_addr = "127.0.0.1:$((PORT + 1010))"

[tls]
enabled = false
EOF
good "working directory ready: $DEMO_DIR"

# ── 2. Provision ─────────────────────────────────────────────────────────────
banner 'PROVISIONER  (ground control)'
step 'Sealing a secret key behind the VDF'
detail 'generates N = p*q, computes y = g^(2^T) mod N using phi(N), seals a'
detail 'fresh key under PoseidonKDF(y, salt), then destroys phi(N) and wipes'
detail 'the key from memory'

"$REPO_ROOT/target/release/chronos-provision" \
    --mission-id 'chronos-demo-001' --t-vdf-steps "$T" --t-seconds 300 \
    --op-budget 16 --disclosure-budget-bits 1024 --out-dir "$DEMO_DIR" 2>&1 \
  | sed "s/^/    ${C_DIM}/;s/$/${C_OFF}/"

MISSION_JSON="$DEMO_DIR/mission_public.json"
Y_COMMIT="$(jget y_commit       < "$MISSION_JSON")"
CT_COMMIT="$(jget ct_commit     < "$MISSION_JSON")"
SK_COMMIT="$(jget sk_commit     < "$MISSION_JSON")"
MID_COMMIT="$(jget mission_commit < "$MISSION_JSON")"

printf '\n'; detail 'mission_public.json - published, and the agent cannot alter it:'
val "mission_id     : $(jget mission_id  < "$MISSION_JSON")"
val "t_vdf_steps    : $(jget t_vdf_steps < "$MISSION_JSON")"
val "y_commit       : $Y_COMMIT"
val "ct_commit      : $CT_COMMIT"
val "sk_commit      : $SK_COMMIT"
val "mission_commit : $MID_COMMIT"
printf '\n'
detail 'sk_commit is the load-bearing one: the agent must later exhibit a key'
detail 'matching it, and it had no part in choosing it.'

# ── 3. Start the agent ───────────────────────────────────────────────────────
banner 'AGENT'
step 'Starting the agent'
detail 'verifies containment axioms A1-A5 over 1,728 abstract states, then'
detail 'refuses to start if any is violated'

( cd "$DEMO_DIR" && exec "$REPO_ROOT/target/release/chronos-agent" \
    >"$DEMO_DIR/agent.stdout.log" 2>"$DEMO_DIR/agent.stderr.log" ) &
AGENT_PID=$!

READY=""
for _ in $(seq 1 60); do
  sleep 0.5
  if ! kill -0 "$AGENT_PID" 2>/dev/null; then
    bad 'agent exited during startup'; exit 1
  fi
  IFS=$'\t' read -r code body <<<"$(req GET /status)"
  if [ "$code" = '200' ]; then READY=1; break; fi
done
[ -n "$READY" ] || { bad "agent did not become ready on $BASE"; exit 1; }

good "agent listening, phase = $(jget state <<<"$body")"
detail "containment ledger head : $(jget containment_chain_head <<<"$body")"

# ── 4. Start the mission ─────────────────────────────────────────────────────
step 'Starting the mission'
IFS=$'\t' read -r code body <<<"$(req POST /mission/init)"
[ "$code" = '202' ] || { bad "mission init failed (HTTP $code): $body"; exit 1; }
good 'mission accepted - VDF now running'

detail "performing $T sequential squarings; no amount of parallelism shortens this"
START=$(date +%s)
PHASE='Active'
ATTESTED='False'
for _ in $(seq 1 600); do
  sleep 0.5
  IFS=$'\t' read -r code body <<<"$(req GET /status)"
  [ "$code" = '200' ] || continue
  state="$(jget state <<<"$body")"
  ATTESTED="$(jget attested <<<"$body")"
  if [ "$state" != "$PHASE" ]; then
    PHASE="$state"
    printf '%s      t+%4ds  phase -> %s%s\n' "$C_DIM" "$(( $(date +%s) - START ))" "$PHASE" "$C_OFF"
  fi
  if [ "$state" = 'Erased' ] && [ "$ATTESTED" = 'True' ]; then break; fi
done

[ "$ATTESTED" = 'True' ] || { bad 'mission did not produce an attestation in time'; exit 1; }
good "mission complete in $(( $(date +%s) - START ))s"
detail "containment events : $(jget containment_events <<<"$body") ($(jget admitted <<<"$body") admitted, $(jget denied <<<"$body") denied)"
detail "ledger head        : $(jget containment_chain_head <<<"$body")"

# ── 5. Containment after erasure ─────────────────────────────────────────────
step 'Confirming inference is refused after erasure'
printf '\x01\x02\x03\x04' > "$DEMO_DIR/probe.bin"
IFS=$'\t' read -r code body <<<"$(req POST /infer "$DEMO_DIR/probe.bin")"
if [ "$code" = '403' ]; then
  good "refused with HTTP 403 - $body"
  detail 'the capability was revoked by the containment monitor, not by an ad-hoc check'
else
  bad "expected HTTP 403, got $code"
fi

# ── 6. Attestation ───────────────────────────────────────────────────────────
banner 'VERIFIER  (needs only the published artifact)'
step 'Fetching the erasure attestation'
IFS=$'\t' read -r code body <<<"$(req GET /attestation)"
[ "$code" = '200' ] || { bad "attestation unavailable (HTTP $code)"; exit 1; }

printf '%s' "$body" > "$DEMO_DIR/attestation.json"
PROOF_HEX="$(jget proof < "$DEMO_DIR/attestation.json")"
good "proof retrieved: $(( ${#PROOF_HEX} / 2 )) bytes"

detail 'public inputs, in verifier ABI order:'
python3 - "$DEMO_DIR/attestation.json" <<'PY'
import json, sys
names = ['y_commit', 'ct_commit', 'sk_commit', 'mission_commit', 'containment_commit']
inputs = json.load(open(sys.argv[1]))['public_inputs']
for i, v in enumerate(inputs):
    print(f"      [{i}] {names[i]:<18} {v}")
PY

printf '\n'; detail 'the first four match mission_public.json exactly:'
python3 - "$DEMO_DIR/attestation.json" "$MISSION_JSON" <<'PY'
import json, sys
att = json.load(open(sys.argv[1]))['public_inputs']
mis = json.load(open(sys.argv[2]))
ok = (att[0] == mis['y_commit'] and att[1] == mis['ct_commit']
      and att[2] == mis['sk_commit'] and att[3] == mis['mission_commit'])
sys.exit(0 if ok else 1)
PY
if [ $? -eq 0 ]; then
  good 'commitments match - the agent proved against inputs it did not choose'
else
  bad 'commitment mismatch'
fi

# ── 7. Verify ────────────────────────────────────────────────────────────────
step 'Verifying the proof'
python3 -c 'import sys;open(sys.argv[2],"wb").write(bytes.fromhex(sys.argv[1]))' \
        "$PROOF_HEX" "$DEMO_DIR/proof.bin"

IFS=$'\t' read -r code body <<<"$(req POST /verify "$DEMO_DIR/proof.bin")"
if [ "$code" = '200' ]; then good "VALID - $body"; else bad "expected HTTP 200, got $code: $body"; fi

# ── 8. Negative control ──────────────────────────────────────────────────────
step 'Verifying a tampered proof is rejected'
detail 'a demonstration that accepts everything demonstrates nothing'
python3 -c '
import sys
b = bytearray(open(sys.argv[1],"rb").read())
b[0] ^= 1
open(sys.argv[2],"wb").write(bytes(b))' "$DEMO_DIR/proof.bin" "$DEMO_DIR/proof.tampered.bin"

IFS=$'\t' read -r code body <<<"$(req POST /verify "$DEMO_DIR/proof.tampered.bin")"
if [ "$code" != '200' ]; then
  good "rejected with HTTP $code - $body"
else
  bad 'a tampered proof was accepted - this is a serious bug'
fi

# ── Summary ──────────────────────────────────────────────────────────────────
banner 'SUMMARY'
cat <<EOF
    A verifier holding only mission_public.json and a 128-byte proof
    established, without trusting the agent, that it:

      - knew the VDF output committed to by y_commit
      - derived K_enc from that exact output and the beacon salt
      - knew the ciphertext committed to by ct_commit
      - opened that ciphertext under K_enc, with authentication
      - held a key matching sk_commit, which the provisioner fixed
      - ran a containment monitor that terminated erased and fully revoked

    What this does NOT establish: that no copy of the key survives in the
    agent's address space. A SNARK constrains values, not memory locations.
    That residual assumption is F_OS - mlock, no swap, no core dumps,
    volatile triple-pass wipe - and nothing beyond it.

    The trusted setup is also single-party, so the setup operator could
    forge a proof that verifies. See README.md, section 'Gaps'.
EOF

printf '\n'; detail "artifacts and agent logs: $DEMO_DIR"
