<#
.SYNOPSIS
    CHRONOS end-to-end demonstration.

.DESCRIPTION
    Walks the full protocol across the provisioner/agent/verifier boundary and
    ends with a verifier accepting a 128-byte proof it can check without trusting
    the agent.

    Nothing here is staged. The VDF performs real sequential squarings, the key is
    genuinely sealed and genuinely opened, and the proof is generated by the agent
    and verified against commitments the agent did not choose.

.NOTES
    Authentication is disabled for this run. That is a legitimate configuration,
    not a shortcut: the agent permits it only when bound to loopback, and refuses
    to start otherwise. Every endpoint would normally also require an
    X-Chronos-Auth HMAC over method, path, nonce and body digest. Reproducing that
    in a shell script would obscure the protocol, which is what this script exists
    to show.

.PARAMETER T
    Sequential squarings. Default 2,000,000 gives roughly 8 seconds of visible
    work at ~505k squarings/sec. Provisioning stays fast regardless, because the
    provisioner uses phi(N) to shortcut.

.PARAMETER Port
    Loopback port for the agent API.

.EXAMPLE
    .\scripts\demo.ps1
    .\scripts\demo.ps1 -T 10000000
#>

[CmdletBinding()]
param(
    [long]$T = 2000000,
    [int]$Port = 8080,
    [switch]$KeepArtifacts
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# ── Presentation helpers ─────────────────────────────────────────────────────
# The terminal output is the story, so the banners matter as much as the logic.

$script:StepNumber = 0

function Write-Banner([string]$Text) {
    Write-Host ''
    Write-Host ('=' * 74) -ForegroundColor DarkCyan
    Write-Host "  $Text" -ForegroundColor Cyan
    Write-Host ('=' * 74) -ForegroundColor DarkCyan
}

function Write-Step([string]$Text) {
    $script:StepNumber++
    Write-Host ''
    Write-Host "[$script:StepNumber] $Text" -ForegroundColor Yellow
}

function Write-Detail([string]$Text) { Write-Host "    $Text" -ForegroundColor Gray }
function Write-Good([string]$Text) { Write-Host "    OK  $Text" -ForegroundColor Green }
function Write-Bad([string]$Text) { Write-Host "    !!  $Text" -ForegroundColor Red }

# ── Paths ────────────────────────────────────────────────────────────────────

$RepoRoot = Split-Path -Parent $PSScriptRoot
$DemoDir = Join-Path $RepoRoot 'demo-run'
$Base = "http://127.0.0.1:$Port"

$AgentProcess = $null

function Stop-Agent {
    if ($script:AgentProcess -and -not $script:AgentProcess.HasExited) {
        Write-Detail 'stopping agent'
        try { $script:AgentProcess.Kill() } catch { }
        try { $script:AgentProcess.WaitForExit(5000) | Out-Null } catch { }
    }
}

# Unauthenticated request helper. A fresh 24-hex-character nonce is still
# required even with auth disabled: replay protection and authentication are
# independent controls, and only the latter is switched off here.
function Invoke-Chronos {
    param(
        [string]$Method,
        [string]$Path,
        [byte[]]$Body
    )
    $nonce = -join ((1..12) | ForEach-Object { '{0:x2}' -f (Get-Random -Minimum 0 -Maximum 256) })
    $headers = @{ 'X-Chronos-Nonce' = $nonce }

    $params = @{
        Uri             = "$Base$Path"
        Method          = $Method
        Headers         = $headers
        TimeoutSec      = 30
        UseBasicParsing = $true
    }
    if ($Body) {
        $params['Body'] = $Body
        $params['ContentType'] = 'application/octet-stream'
    }

    try {
        $resp = Invoke-WebRequest @params
        return @{ Ok = $true; Status = [int]$resp.StatusCode; Content = $resp.Content }
    }
    catch {
        $status = 0
        if ($_.Exception.Response) { $status = [int]$_.Exception.Response.StatusCode }
        return @{ Ok = $false; Status = $status; Content = $_.ErrorDetails.Message }
    }
}

try {
    Write-Banner 'CHRONOS - end-to-end demonstration'
    Write-Detail "repository : $RepoRoot"
    Write-Detail "T          : $T sequential squarings"
    Write-Detail "API        : $Base (loopback, authentication disabled)"

    # ── 0. Build ─────────────────────────────────────────────────────────────
    Write-Step 'Building release binaries'
    Write-Detail 'first run compiles the dependency tree; subsequent runs are fast'
    $oldError = $ErrorActionPreference; $ErrorActionPreference = 'Continue'
    & cargo build --release -p chronos-provision -p chronos-agent -q 2>&1 | Out-Null
    $ErrorActionPreference = $oldError
    if ($LASTEXITCODE -ne 0) { throw 'cargo build failed - run it directly to see the error' }
    Write-Good 'chronos-provision and chronos-agent built'

    # ── 1. Clean working directory ───────────────────────────────────────────
    Write-Step 'Preparing a clean working directory'
    if (Test-Path $DemoDir) { Remove-Item -Recurse -Force $DemoDir }
    New-Item -ItemType Directory -Path $DemoDir -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $DemoDir 'config') -Force | Out-Null

    # The agent loads config/default.toml relative to its working directory, and
    # that source is required rather than optional, so it must exist here.
    @"
# Generated by scripts/demo.ps1 - not for production use.
[paths]
mission_public = "mission_public.json"
ct_sk          = "ct_sk.bin"
salt           = "salt.bin"
cert_n         = "certN.bin"
proving_key    = "erasure_pk.bin"

[auth]
# Permitted only because api_addr below is loopback. The agent refuses to start
# with authentication disabled on any routable address.
enabled = false

[network]
drand_url          = "https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971/public/latest"
drand_timeout_secs = 10
# The sealing key is derived from (y, salt), so the salt must be the one the
# provisioner sealed under. A live beacon would be a different value.
fetch_live_beacon  = false

[server]
api_addr     = "127.0.0.1:$Port"
metrics_addr = "127.0.0.1:$($Port + 1010)"

[tls]
enabled = false
"@ | Set-Content -Path (Join-Path $DemoDir 'config\default.toml') -Encoding ascii

    Write-Good "working directory ready: $DemoDir"

    # ── 2. Provision ─────────────────────────────────────────────────────────
    Write-Banner 'PROVISIONER  (ground control)'
    Write-Step 'Sealing a secret key behind the VDF'
    Write-Detail 'generates N = p*q, computes y = g^(2^T) mod N using phi(N),'
    Write-Detail 'seals a fresh key under PoseidonKDF(y, salt), then destroys'
    Write-Detail 'phi(N) and wipes the key from memory'

    & cargo run --release -q -p chronos-provision -- --mission-id 'chronos-demo-001' --t-vdf-steps $T --t-seconds 300 `
                 --op-budget 16 --disclosure-budget-bits 1024 --out-dir $DemoDir 2>&1 |
    ForEach-Object { Write-Detail $_ }
    if ($LASTEXITCODE -ne 0) { throw 'provisioning failed' }

    $missionJson = Get-Content (Join-Path $DemoDir 'mission_public.json') -Raw | ConvertFrom-Json

    Write-Host ''
    Write-Detail 'mission_public.json - published, and the agent cannot alter it:'
    Write-Host "      mission_id     : $($missionJson.mission_id)"       -ForegroundColor White
    Write-Host "      t_vdf_steps    : $($missionJson.t_vdf_steps)"      -ForegroundColor White
    Write-Host "      y_commit       : $($missionJson.y_commit)"         -ForegroundColor White
    Write-Host "      ct_commit      : $($missionJson.ct_commit)"        -ForegroundColor White
    Write-Host "      sk_commit      : $($missionJson.sk_commit)"        -ForegroundColor White
    Write-Host "      mission_commit : $($missionJson.mission_commit)"   -ForegroundColor White
    Write-Host ''
    Write-Detail 'sk_commit is the load-bearing one: the agent must later exhibit'
    Write-Detail 'a key matching it, and it had no part in choosing it.'

    # ── 3. Start the agent ───────────────────────────────────────────────────
    Write-Banner 'AGENT'
    Write-Step 'Starting the agent'
    Write-Detail 'verifies containment axioms A1-A5 over 1,728 abstract states,'
    Write-Detail 'then refuses to start if any is violated'

    $agentExe = Join-Path $RepoRoot 'target\release\chronos-agent.exe'
    $stdout   = Join-Path $DemoDir 'agent.stdout.log'
    $stderr   = Join-Path $DemoDir 'agent.stderr.log'

    $script:AgentProcess = Start-Process -FilePath $agentExe -WorkingDirectory $DemoDir `
        -RedirectStandardOutput $stdout -RedirectStandardError $stderr `
        -PassThru -WindowStyle Hidden

    $ready = $false
    foreach ($attempt in 1..60) {
        Start-Sleep -Milliseconds 500
        if ($script:AgentProcess.HasExited) {
            Write-Bad "agent exited with code $($script:AgentProcess.ExitCode)"
            Write-Host (Get-Content $stderr -Raw) -ForegroundColor DarkRed
            throw 'agent failed to start'
        }
        $probe = Invoke-Chronos -Method GET -Path '/status'
        if ($probe.Ok) { $ready = $true; break }
    }
    if (-not $ready) { throw "agent did not become ready on $Base" }

    $status = $probe.Content | ConvertFrom-Json
    Write-Good "agent listening, phase = $($status.state)"
    Write-Detail "containment ledger head : $($status.containment_chain_head)"

    # ── 4. Start the mission ─────────────────────────────────────────────────
    Write-Step 'Starting the mission'
    $init = Invoke-Chronos -Method POST -Path '/mission/init'
    if (-not $init.Ok) { throw "mission init failed (HTTP $($init.Status)): $($init.Content)" }
    Write-Good 'mission accepted - VDF now running'

    Write-Detail "performing $T sequential squarings; no amount of parallelism shortens this"
    $sw = [Diagnostics.Stopwatch]::StartNew()
    $phase = 'Active'
    foreach ($attempt in 1..600) {
        Start-Sleep -Milliseconds 500
        $s = Invoke-Chronos -Method GET -Path '/status'
        if (-not $s.Ok) { continue }
        $status = $s.Content | ConvertFrom-Json
        if ($status.state -ne $phase) {
            $phase = $status.state
            Write-Detail ("  t+{0,6:N1}s  phase -> {1}" -f $sw.Elapsed.TotalSeconds, $phase)
        }
        if ($status.state -eq 'Erased' -and $status.attested) { break }
    }
    $sw.Stop()

    if (-not $status.attested) { throw 'mission did not produce an attestation in time' }
    Write-Good ("mission complete in {0:N1}s" -f $sw.Elapsed.TotalSeconds)
    Write-Detail "containment events : $($status.containment_events) ($($status.admitted) admitted, $($status.denied) denied)"
    Write-Detail "ledger head        : $($status.containment_chain_head)"

    # ── 5. Containment after erasure ─────────────────────────────────────────
    Write-Step 'Confirming inference is refused after erasure'
    $infer = Invoke-Chronos -Method POST -Path '/infer' -Body ([byte[]](1, 2, 3, 4))
    if ($infer.Status -eq 403) {
        Write-Good "refused with HTTP 403 - $($infer.Content)"
        Write-Detail 'the capability was revoked by the containment monitor, not by an ad-hoc check'
    }
    else {
        Write-Bad "expected HTTP 403, got $($infer.Status)"
    }

    # ── 6. Attestation ───────────────────────────────────────────────────────
    Write-Banner 'VERIFIER  (needs only the published artifact)'
    Write-Step 'Fetching the erasure attestation'
    $att = Invoke-Chronos -Method GET -Path '/attestation'
    if (-not $att.Ok) { throw "attestation unavailable (HTTP $($att.Status))" }
    $attestation = $att.Content | ConvertFrom-Json

    $proofHex = $attestation.proof
    Write-Good "proof retrieved: $($proofHex.Length / 2) bytes"
    Write-Detail 'public inputs, in verifier ABI order:'
    $names = @('y_commit', 'ct_commit', 'sk_commit', 'mission_commit', 'containment_commit')
    for ($i = 0; $i -lt $attestation.public_inputs.Count; $i++) {
        Write-Host ("      [{0}] {1,-18} {2}" -f $i, $names[$i], $attestation.public_inputs[$i]) -ForegroundColor White
    }

    Write-Host ''
    Write-Detail 'the first four match mission_public.json exactly:'
    $matched = ($attestation.public_inputs[0] -eq $missionJson.y_commit) -and
    ($attestation.public_inputs[1] -eq $missionJson.ct_commit) -and
    ($attestation.public_inputs[2] -eq $missionJson.sk_commit) -and
    ($attestation.public_inputs[3] -eq $missionJson.mission_commit)
    if ($matched) {
        Write-Good 'commitments match - the agent proved against inputs it did not choose'
    }
    else {
        Write-Bad 'commitment mismatch'
    }

    # ── 7. Verify ────────────────────────────────────────────────────────────
    Write-Step 'Verifying the proof'
    $proofBytes = [byte[]]::new($proofHex.Length / 2)
    for ($i = 0; $i -lt $proofBytes.Length; $i++) {
        $proofBytes[$i] = [Convert]::ToByte($proofHex.Substring($i * 2, 2), 16)
    }

    $verify = Invoke-Chronos -Method POST -Path '/verify' -Body $proofBytes
    if ($verify.Status -eq 200) {
        Write-Good "VALID - $($verify.Content)"
    }
    else {
        Write-Bad "expected HTTP 200, got $($verify.Status): $($verify.Content)"
    }

    # ── 8. Negative control ──────────────────────────────────────────────────
    Write-Step 'Verifying a tampered proof is rejected'
    Write-Detail 'a demonstration that accepts everything demonstrates nothing'
    $tampered = $proofBytes.Clone()
    $tampered[0] = $tampered[0] -bxor 0x01
    $bad = Invoke-Chronos -Method POST -Path '/verify' -Body $tampered
    if ($bad.Status -ne 200) {
        Write-Good "rejected with HTTP $($bad.Status) - $($bad.Content)"
    }
    else {
        Write-Bad 'a tampered proof was accepted - this is a serious bug'
    }

    # ── Summary ──────────────────────────────────────────────────────────────
    Write-Banner 'SUMMARY'
    Write-Host @"
    A verifier holding only mission_public.json and a 128-byte proof
    established, without trusting the agent, that it:

      - knew the VDF output committed to by y_commit
      - derived K_enc from that exact output and the beacon salt
      - knew the ciphertext committed to by ct_commit
      - opened that ciphertext under K_enc, with authentication
      - held a key matching sk_commit, which the provisioner fixed
      - ran a containment monitor that terminated erased and fully revoked

    What this does NOT establish: that no copy of the key survives in the
    agent's address space. A SNARK constrains values, not memory locations.
    That residual assumption is F_OS - mlock, no swap, no core dumps,
    volatile triple-pass wipe - and nothing beyond it.

    The trusted setup is also single-party, so the setup operator could
    forge a proof that verifies. See README.md, section 'Gaps'.
"@ -ForegroundColor White

    Write-Host ''
    Write-Detail "artifacts and agent logs: $DemoDir"
}
catch {
    Write-Host ''
    Write-Bad $_.Exception.Message
    if (Test-Path (Join-Path $DemoDir 'agent.stderr.log')) {
        Write-Host ''
        Write-Detail 'agent stderr (last 40 lines):'
        Get-Content (Join-Path $DemoDir 'agent.stderr.log') -Tail 40 |
        ForEach-Object { Write-Host "      $_" -ForegroundColor DarkGray }
    }
    exit 1
}
finally {
    Stop-Agent
    if (-not $KeepArtifacts -and (Test-Path $DemoDir)) {
        Write-Detail 'removing working directory (pass -KeepArtifacts to retain it)'
        Remove-Item -Recurse -Force $DemoDir -ErrorAction SilentlyContinue
    }
    Write-Host ''
}
