//! Generate a Groth16 setup for the erasure circuit and print everything needed
//! to deploy and call the on-chain verifier.
//!
//! ```bash
//! cargo run -p chronos-snark --release --example export_solidity
//! ```
//!
//! Emits the `Groth16Verifier` constructor arguments, then a sample proof in EVM
//! calldata form so the deployment can be smoke-tested end to end.
//!
//! The setup produced here is single-party — this process holds the trapdoor.
//! It is fine for a testnet deployment and for verifying the encoding is
//! correct. It is not suitable for a deployment where the verifier does not
//! trust whoever ran this command.

use chronos_snark::prover::Groth16Prover;
use chronos_snark::solidity::{
    erasure_public_inputs, export_proof, export_verifying_key, ERASURE_PUBLIC_INPUT_COUNT,
};
use chronos_snark::circuit::WIPE_PATTERN;

use ark_bn254::Bn254;
use ark_groth16::Proof;
use ark_serialize::CanonicalDeserialize;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    eprintln!("Generating Groth16 setup for ErasureCircuit...");
    let mut prover = Groth16Prover::new();
    prover.generate_keys()?;

    let vk = prover.verifying_key()?;
    let sol_vk = export_verifying_key(vk)?;

    if sol_vk.public_input_count() != ERASURE_PUBLIC_INPUT_COUNT {
        return Err(format!(
            "verifying key declares {} public inputs, contracts expect {}",
            sol_vk.public_input_count(),
            ERASURE_PUBLIC_INPUT_COUNT
        )
        .into());
    }

    println!("// ─────────────────────────────────────────────────────────────");
    println!("// Groth16Verifier deployment arguments");
    println!("// Generated by: cargo run -p chronos-snark --release --example export_solidity");
    println!("// WARNING: single-party setup. This process held the trapdoor.");
    println!("// ─────────────────────────────────────────────────────────────");
    println!();
    print!("{}", sol_vk.to_constructor_args());
    println!();

    // Produce a real proof so the encoding can be smoke-tested on-chain.
    let sk = vec![WIPE_PATTERN; 32];
    let m_pre = vec![0xDEu8; 32];
    let y = vec![0xABu8; 32];
    let salt = vec![0xCDu8; 32];
    let ct_sk = vec![0x00u8; 48];
    let g = vec![0x02u8; 32];
    let n_mod = vec![0x01u8; 32];
    let pi_vdf = vec![0x03u8; 32];

    eprintln!("Generating a sample proof...");
    let proof_bytes =
        prover.prove_erasure(&sk, &m_pre, &y, &salt, &ct_sk, &g, &n_mod, &pi_vdf)?;

    // Confirm it verifies natively before claiming it should verify on-chain.
    let ok = prover.verify_erasure(&proof_bytes, y[0], WIPE_PATTERN)?;
    if !ok {
        return Err("sample proof failed native verification — aborting".into());
    }
    eprintln!("Sample proof verifies natively.");

    let proof = Proof::<Bn254>::deserialize_compressed(&proof_bytes[..])?;
    let sol_proof = export_proof(&proof)?;
    let inputs = erasure_public_inputs(y[0], WIPE_PATTERN);

    println!("// ─────────────────────────────────────────────────────────────");
    println!("// Sample proof — verifies natively, use to smoke-test the deployment");
    println!("// ─────────────────────────────────────────────────────────────");
    println!("// public inputs: [y[0], WIPE_PATTERN] = [{}, {}]", inputs[0], inputs[1]);
    println!();
    println!("// cast call <VERIFIER> \\");
    println!("//   \"verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[2])\" \\");
    println!("//   {} \\", sol_proof.to_calldata_args());
    println!("//   \"[{},{}]\"", inputs[0], inputs[1]);
    println!();
    println!("// Expected result: true");

    Ok(())
}
